POST http://localhost:3003/api/blogs/614d6dca8d9acb6189a690fc/comments
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1hdHR5RXYiLCJpZCI6IjYxMzFiZGZlNGMzMTRhYjU0NTM3NDhlZSIsImlhdCI6MTYzMDY1NDM2Nn0.y2FrUCwX0FpRIVCZK7EWzVKyqSyW1_clS7DBmJyRuzk

{
    "content": "hey"
}